In [0]:
import pandas as pd
import numpy as np


In [0]:
column_names = ['JokeCount'] + [f'Joke{num + 1}' for num in range(100)]
df = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab5-recommender/jester-data-1.csv',header=None, names=column_names)

In [21]:
dataframe = df.drop(columns=['JokeCount'])
x= dataframe.values
print(x.shape)

(24983, 100)


In [0]:
def replace(original, percentage=0.1):
  new_data = original.copy()
  rated = np.where(x!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])



In [22]:
new_x, idx = replace(x, 0.1)
rated = np.where(x!=99)
new_rated = np.where(new_x!=99)
print(len(rated[0]), rated[1].shape)

1810455 (1810455,)


In [42]:
n_latent_factors = 2

user_ratings = new_x
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

print(user_ratings)

[[-7.82  8.79 -9.66 ... 99.   99.   99.  ]
 [ 4.08 -0.29  6.36 ...  0.34 -4.32  1.07]
 [99.   99.   99.   ... 99.   99.   99.  ]
 ...
 [99.   99.   99.   ... 99.   99.   99.  ]
 [99.   99.   99.   ... 99.   99.   99.  ]
 [ 2.43  2.67 -3.98 ... 99.   99.   99.  ]]


In [0]:
def predict_rating(user_id, item_id):
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)

def train(user_id, item_id, rating, alpha=0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]

    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values

    
    return err
    

def sgd(iterations=100):
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if rating != 99:
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 10) == 0:
            print(mse)

In [50]:
sgd()

22.87280286377694
18.46733620306312
17.495675919723727
17.253735905753164
16.987850925689646
16.573928111109836
16.04307138055244
15.538251794300002
15.164440282204753
14.923098151941703


In [54]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[-2.95295612, -2.51214893, -6.0108158 , ..., -2.72743743,
        -7.63098737, -3.70262349],
       [ 1.33121429,  1.91520732,  3.02617371, ...,  4.06466473,
         4.34267315,  4.45531163],
       [ 6.87602977,  4.65271837,  5.87011237, ...,  7.17741111,
         8.41495533,  7.15567856],
       ...,
       [-1.08701616, -0.17005071, -2.25530525, ..., -0.76380538,
        -3.48715017, -1.23261243],
       [-1.96823151, -2.58650354, -4.46812035, ..., -0.89928965,
        -3.64783866, -2.03845329],
       [ 2.30392425,  1.23710248,  1.06049164, ...,  5.40615784,
         3.76658936,  4.80460741]])

In [55]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data

0  ...                           99
0      (-7.82, -2.952956122557951)  ...   (99.0, -3.702623488199062)
1       (4.08, 1.3312142907790632)  ...    (1.07, 4.455311625478073)
2        (99.0, 6.876029771438107)  ...    (99.0, 7.155678555065309)
3      (99.0, 0.15974032581216427)  ...    (99.0, 6.191267278818015)
4         (8.5, 2.104541234684532)  ...     (1.6, 5.723033348554435)
...                            ...  ...                          ...
24978    (0.44, 0.673422563676711)  ...    (7.43, 5.543979807028721)
24979   (9.13, 1.0663302917110724)  ...   (8.45, 3.6867835998579475)
24980  (99.0, -1.0870161618801784)  ...  (99.0, -1.2326124277645318)
24981  (99.0, -1.9682315094925587)  ...   (99.0, -2.038453288871069)
24982    (2.43, 2.303924246407978)  ...    (99.0, 4.804607409496675)

[24983 rows x 100 columns]

In [56]:
n_latent_factors = 5
user_ratings = x
latent_user_preferences=np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features=np.random.random((user_ratings.shape[1],n_latent_factors))
sgd()
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions


25.572412467358788
24.015454600322997
21.39314615950442
17.81162634597321
17.39698617908974
17.1684014172776
16.861629200504762
16.452975049051457
15.999242510461405
15.577278794021607


array([[-3.46926959, -3.32218102, -5.79805469, ..., -4.05991754,
        -6.38561542, -4.56387645],
       [ 3.04593844,  3.25011825,  4.32052918, ...,  4.02836763,
         3.1092554 ,  4.83612983],
       [ 5.83120977,  6.1628579 ,  6.61422971, ...,  7.50745989,
         7.28922745,  8.24634464],
       ...,
       [-2.30056581, -0.96090207, -2.13496708, ...,  0.16165307,
        -2.16110752,  0.12595714],
       [-1.96242963, -0.09812465, -2.41686278, ..., -0.0190166 ,
        -5.45351865,  0.46306429],
       [ 3.3359256 ,  2.54697426,  2.83968273, ...,  3.19770867,
         2.19336291,  3.76213506]])

In [57]:

values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data= pd.DataFrame(values)
comparison_data

0  ...                           99
0      (-7.82, -3.469269585136326)  ...   (99.0, -4.563876450400107)
1        (4.08, 3.045938440308413)  ...    (1.07, 4.836129833903556)
2        (99.0, 5.831209768628038)  ...    (99.0, 8.246344636663194)
3        (99.0, 4.715743286523116)  ...   (99.0, 4.3109497408101864)
4        (8.5, 2.2832232884310484)  ...     (1.6, 5.247296315669443)
...                            ...  ...                          ...
24978     (0.44, 1.38368992709237)  ...    (7.43, 4.841868196367775)
24979    (9.13, 4.455041804355887)  ...    (8.45, 3.975501099387558)
24980   (99.0, -2.300565805186666)  ...   (99.0, 0.1259571418618704)
24981  (99.0, -1.9624296293644876)  ...  (99.0, 0.46306429321951037)
24982   (2.43, 3.3359256000970956)  ...   (99.0, 3.7621350604987636)

[24983 rows x 100 columns]